sudo: false
branches:
  only:
  - develop
language: ruby
rvm:
- 2.2.0
install:
- travis_retry gem install jekyll
- travis_retry gem install kramdown -v 1.7.0
- travis_retry gem install jekyll-sitemap
- travis_retry gem install html-proofer
- travis_retry npm install -g bower
- travis_retry npm install -g grunt-cli
before_script:
- npm install
- bower install
script:
- grunt tests
- grunt build
after_success:
- htmlproof ./_site --only-4xx
- bash ./script.bash
notifications:
  email: rapha.fabeni@gmail.com
env:
  global:
    secure: mQD7tw5fQCMvcx3Tt2oM54dtnXL67CdFBSd12/82b66k94YLhRfnuyFKjS7avAovsGR95H9ZZ+Ix+sWMSjuzfu50Xrk1Bo8CL/aUqIphtK0C7wM4oGSUXFTYwcRTQZzYx3CcsH31roK8ViSVG8cLBJb0aJyYm/E7CuE/qqS725s=
