sudo: false
branches:
  only:
  - develop
language: ruby
rvm:
- 2.2.0
install:
- bash ./script.bash
notifications:
  email: rapha.fabeni@gmail.com
env:
  global:
    secure: mQD7tw5fQCMvcx3Tt2oM54dtnXL67CdFBSd12/82b66k94YLhRfnuyFKjS7avAovsGR95H9ZZ+Ix+sWMSjuzfu50Xrk1Bo8CL/aUqIphtK0C7wM4oGSUXFTYwcRTQZzYx3CcsH31roK8ViSVG8cLBJb0aJyYm/E7CuE/qqS725s=
