language: node_js
node_js:
  - "0.10"
install:
  - travis_retry gem install  jekyll
  - travis_retry npm install -g bower
  - travis_retry npm install -g grunt-cli
before_script:
  - npm install
  - bower install
script:
  - grunt build
  - grunt tests
notifications:
  email:
    rapha.fabeni@gmail.com
