branches:
  only:
    - develop
language: node_js
node_js:
  - "0.10"
install:
  - travis_retry gem install  jekyll
  - travis_retry npm install -g bower
  - travis_retry npm install -g grunt-cli
  - travis_retry gem install jekyll-sitemap
  - travis_retry gem install html-proofer
before_script:
  - npm install
  - bower install
script:
  - grunt tests
  - grunt build
  - htmlproof ./_site --only-4xx
  - bash script.bash
notifications:
  email:
    rapha.fabeni@gmail.com
