language: node_js
node_js:
  - "0.10"
install:
  - travis_retry gem install  jekyll
  - travis_retry npm install -g bower
  - travis_retry npm install -g grunt-cli
before_script:
  - npm install
  - bower install
script:
  - grunt tests
  - grunt build
after_success:
  - ./node_modules/.bin/jscoverage lib lib-cov
notifications:
  email:
    rapha.fabeni@gmail.com
