language: node_js
node_js:
  - "0.10"
install:
  - travis_retry gem install --no-document jekyll
  - travis_retry npm install -g bower
  - travis_retry npm install -g grunt-cli
before_script:
  - npm install
  - bower install
script:
  - grunt build
after_script:
  - npm run-script coveralls
notifications:
  email:
    rapha.fabeni@gmail.com
