language: node_js
node_js:
  - "0.10"
install:
  - gem install  jekyll --no-rdoc
  - npm install -g bower
  - npm install -g grunt-cli
before_script:
  - npm install
  - bower install
script:
  - grunt build
  - grunt tests
notifications:
  email:
    rapha.fabeni@gmail.com
