# Site settings
title: Raphael Fabeni
email: contato@raphaelfabeni.com.br
description: "A brazilian front-end developer who loves the web, electronic music and travels."
baseurl: "/"
url: "http://raphaelfabeni.com.br"
exclude: ['node_modules', 'Gruntfile.js', 'package.json']

twitter_username: raphaelfabeni
github_username:  raphaelfabeni

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge

source:      .
destination: ./_site
plugins:     ./_plugins
paginate_path: 'blog/page:num'

permalink:   /:title/
paginate: 5
